# Canary by 
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 5
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: my-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      containers:
      - name: my-app
        image: phuongnguyen1996/canary-demo:0.0.3
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 8086
        - name: metrics
          containerPort: 9101
        env:
        - name: VERSION
          value: v1.0.16
        livenessProbe:
          httpGet:
            path: /live
            port: probe
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: probe
          periodSeconds: 5
        resources:
          requests:
            cpu: 25m
            memory: 50Mi
          limits:
            cpu: 150m
            memory: 150Mi
  strategy:
    canary:
      stableMetadata:
        labels:
          role: stable
      canaryMetadata:
        labels:
          role: canary
      stableService: my-app-stable
      canaryService: my-app-canary
      trafficRouting:
        nginx:
          stableIngress: my-app-ingress-stable
          additionalIngressAnnotations:   # optional
          # To hit canary pod: curl -H "X-Canary: always" http://rollouts-demo.local/
          # To hit stable pod: curl -H "X-Canary: never" http://rollouts-demo.local/
            canary-by-header: X-Canary
      analysis:
        templates:
        - templateName: error-rate
        # delay starting analysis run until setWeight: 50%
        startingStep: 9
        args:
        - name: service-name
          value: my-app
      steps:
      - setWeight: 10
      - pause: { duration: 10 }
      - setWeight: 20
      - pause: { duration: 10 }
      - setWeight: 30
      - pause: { duration: 10 }
      - setWeight: 40
      - pause: { duration: 10 }
      - setWeight: 50
      - pause: {}
