apiVersion: v1
kind: Service
metadata:
  name: my-app-stable
  labels:
    app: my-app-stable
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: my-app
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-canary
  labels:
    app: my-app-canary
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: my-app